name: Report Build / Installation Related Issue
description: Report an issue if you have trouble building or installing Open3D.
title: "Comprehensive title for the build/install issue report."
labels: [build/install issue]

body:
- type: textarea
  attributes:
    label: "Steps to reproduce:"
    description: >
      Thank you for taking the time to file a build/installation related issue 
      report. Before creating a new issue, please be sure to take a few minutes
      to check the issue tracker for existing `build/install issue`. 

      Before submitting issue:
        1. Search for [similar issues](https://github.com/isl-org/Open3D/issues).
        2. For Python issues, please test with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip). It may be already fixed!
        3. Please check with the documentation properly.
          3.a. [Installing from PyPI or Conda](http://www.open3d.org/docs/latest/getting_started.html#installing-from-pypi-or-conda).
          3.b. [Build from source](http://www.open3d.org/docs/latest/compilation.html#build-from-source).
          3.c. [Experimental ARM Support](http://www.open3d.org/docs/latest/arm.html#arm-support).

      Please describe the installation method in detail (e.g. building from 
      source, Anaconda, pip). Share all the steps/commands you used to 
      build/install Open3D. 
  validations:
    required: true

- type: textarea
  attributes:
    label: "Error message:"
    description: >
      Please include `FULL` error message, if any.
      If you are reporting a segfault, please include a GDB traceback.
    placeholder: |
      << Full traceback >>
    render: shell

- type: textarea
  attributes:
    label: "Additional information:"
    description: >
      Please add any additional information that could help us diagnose the 
      problem better. You may even attach log files, generated wheel, 
      screenshots or any other files, that could be helpful.

- type: textarea
  attributes:
    label: "System and Open3D/Python version information:"
    description: >
      Output from `import sys, open3d; print(open3d.__version__, sys.version)`.
        - Operating system: (e.g. OSX 10.15, Ubuntu 18.04, Windows 10 64-bit)
        - Python version: (e.g. Python 3.8 / output from `import sys  print(sys.version)`)
        - Open3D version: (output from python: `print(open3d.__version__)`)
        - System type: (x84 / arm / m1 / aarch / jetson-nano / jetson-tx / rpi)
        - Is this remote workstation?: yes or no
        - How did you install Open3D?: (e.g. pip, conda, build from source)
        - Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)
    placeholder: |
      - Operating system: (e.g. OSX 10.15, Ubuntu 18.04, Windows 10 64-bit)
      - Python version: (e.g. Python 3.8 / output from `import sys  print(sys.version)`)
      - Open3D version: (output from python: `print(open3d.__version__)`)
      - System type: (x84 / arm / m1 / aarch / jetson-nano / jetson-tx / rpi)
      - Is this remote workstation?: yes or no
      - How did you install Open3D?: (e.g. pip, conda, build from source)
      - Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)
  validations:
    required: true
