name: Feature Request
description: New feature request.
title: "Comprehensive title for the feature issue report"
labels: [feature request]

body:
- type: markdown
  attributes:
    value: >
        If you're looking to request a new feature or change in functionality,
        including adding or changing the meaning of arguments to an existing 
        function.

- type: textarea
  attributes:
    label: "Proposed new feature or change:"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Additional information:"
    description: Add any other context or screenshots about the feature request here.