name: Feature Request
description: New feature request.
title: "Comprehensive title for the feature issue report"
labels: [feature request]

body:
- type: checkboxes
  attributes:
    label: "I confirm that before submitting the issue I have taken the following steps:"
    description: It is required to mark the checkboxes, before submitting the issue.
    options:
      - label: "I have searched for [similar issues](https://github.com/isl-org/Open3D/issues)."
        required: true
      - label: "I have checked with the [latest documentation](http://www.open3d.org/docs/latest/) properly. [For example: [Installing from PyPI](http://www.open3d.org/docs/latest/getting_started.html#installing-from-pypi-or-conda), [Build from source](http://www.open3d.org/docs/latest/compilation.html#build-from-source), [ARM Support](http://www.open3d.org/docs/latest/arm.html#arm-support)]."
        required: true

- type: markdown
  attributes:
    value: >
        If you're looking to request a new feature or change in functionality,
        including adding or changing the meaning of arguments to an existing 
        function.

- type: textarea
  attributes:
    label: "Proposed new feature or change:"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Additional information:"
    description: Add any other context or screenshots about the feature request here.