name: Documentation
description: Report an issue related to the Open3D documentation.
title: "Comprehensive title for the documentation issue report."
labels: [docs]

body:
- type: textarea
  attributes: 
    label: "Issue with current documentation:"
    description: >
      Please make sure to leave a reference to the document/code you're
      referring to. You can also check the development version of the
      documentation and see if this issue has already been addressed at
      http://www.open3d.org/docs/latest/.

- type: textarea
  attributes:
    label: "Idea or request for content:"
    description: >
      Please describe as clearly as possible what topics you think are missing
      from the current documentation.