name: Feature Request
description: Describe the missing feature, you would like to be a part of Open3D.
title: "Comprehensive title for the feature request"
labels: [feature request]

body:
- type: markdown
  attributes:
    value: >


- type: textarea
  attributes:
    label: "Proposed new feature or change:"
  validations:
    required: true