name: Feature Request
description: Check instructions for submitting your idea on the mailing list first.
title: "FR: <Please write a comprehensive title after the 'FR: ' prefix>"

body:
- type: markdown
  attributes:
    value: >


- type: textarea
  attributes:
    label: "Proposed new feature or change:"
  validations:
    required: true